In [1]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

In [2]:
import numpy as np

## Working with data


In [3]:
# Download training data from open datasets.
training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor(),
)

# Download test data from open datasets.
test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor(),
)

In [4]:
batch_size = 64

# Create data loaders.
train_dataloader = DataLoader(training_data, batch_size=batch_size)
test_dataloader = DataLoader(test_data, batch_size=batch_size)

for X, y in test_dataloader:
    print(f"Shape of X [N, C, H, W]: {X.shape}")
    print(f"Shape of y: {y.shape} {y.dtype}")
    break

Shape of X [N, C, H, W]: torch.Size([64, 1, 28, 28])
Shape of y: torch.Size([64]) torch.int64


In [5]:
"""
N: number of instaces
C: channel?
H: height
W: width
"""

'\nN: number of instaces\nC: channel?\nH: height\nW: width\n'

## Creating Models


In [6]:
# simple situation
# Ref. https://pytorch.org/tutorials/beginner/basics/buildmodel_tutorial.html
input_image = torch.rand(3, 28, 28)
print(input_image.size())

torch.Size([3, 28, 28])


In [7]:
# flatten -> [3, 28*28]
flatten = nn.Flatten()
flat_image = flatten(input_image)
print(flat_image.size())
print(flat_image)

torch.Size([3, 784])
tensor([[0.2292, 0.3757, 0.7355,  ..., 0.7391, 0.0550, 0.7842],
        [0.7867, 0.9777, 0.0794,  ..., 0.0380, 0.9203, 0.0961],
        [0.1402, 0.2499, 0.3389,  ..., 0.2852, 0.3338, 0.5547]])


In [8]:
# value * weight
layer1 = nn.Linear(in_features=28 * 28, out_features=20)  # fully connected
hidden1 = layer1(flat_image)  # linear transformation (calc hiddlen unit value)
print(hidden1.size())
print(hidden1)

torch.Size([3, 20])
tensor([[ 0.0995,  0.4850, -0.3284, -0.7079, -0.3284, -0.1363,  0.1216,  0.0284,
         -0.1739, -0.3476,  0.4148, -0.0874, -0.4659, -0.1714, -0.1387, -0.2730,
         -0.0262,  0.0690,  0.0445,  0.3326],
        [-0.0581,  0.2906, -0.1834, -0.3370, -0.4961,  0.0802,  0.3361,  0.1041,
         -0.1488, -0.3711,  0.1129, -0.1280, -0.3948, -0.5283,  0.1670, -0.3716,
          0.1771, -0.1842,  0.0365,  0.0681],
        [ 0.0605,  0.1450, -0.0365, -0.5387, -0.3598,  0.2369,  0.1396, -0.0736,
         -0.1854, -0.3234,  0.1599, -0.1212, -0.4196, -0.2987, -0.0711, -0.2420,
          0.2051, -0.4523,  0.1903,  0.0351]], grad_fn=<AddmmBackward0>)


In [9]:
# weight
print(layer1.weight.shape)
print(layer1.weight)

# bias
print(layer1.bias)

torch.Size([20, 784])
Parameter containing:
tensor([[-0.0058, -0.0111, -0.0012,  ..., -0.0049,  0.0096,  0.0224],
        [-0.0283,  0.0021, -0.0329,  ..., -0.0265, -0.0109,  0.0253],
        [ 0.0242, -0.0110,  0.0323,  ..., -0.0162, -0.0244,  0.0133],
        ...,
        [ 0.0223, -0.0017,  0.0133,  ..., -0.0186,  0.0326,  0.0133],
        [-0.0295, -0.0273,  0.0248,  ...,  0.0249,  0.0084,  0.0029],
        [ 0.0216,  0.0187,  0.0274,  ...,  0.0231,  0.0193, -0.0230]],
       requires_grad=True)
Parameter containing:
tensor([ 0.0184, -0.0219, -0.0164,  0.0269, -0.0312,  0.0355, -0.0018, -0.0248,
         0.0198, -0.0067, -0.0168, -0.0241,  0.0089,  0.0005,  0.0198, -0.0155,
         0.0142,  0.0143, -0.0290,  0.0346], requires_grad=True)


In [10]:
# ReLU
hidden_activate = nn.ReLU()(hidden1)
print(hidden_activate)


# compare
def relu(x):
    return np.maximum(0, x)


print("compare: \n", relu(hidden1.detach().numpy()))

tensor([[0.0995, 0.4850, 0.0000, 0.0000, 0.0000, 0.0000, 0.1216, 0.0284, 0.0000,
         0.0000, 0.4148, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0690,
         0.0445, 0.3326],
        [0.0000, 0.2906, 0.0000, 0.0000, 0.0000, 0.0802, 0.3361, 0.1041, 0.0000,
         0.0000, 0.1129, 0.0000, 0.0000, 0.0000, 0.1670, 0.0000, 0.1771, 0.0000,
         0.0365, 0.0681],
        [0.0605, 0.1450, 0.0000, 0.0000, 0.0000, 0.2369, 0.1396, 0.0000, 0.0000,
         0.0000, 0.1599, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.2051, 0.0000,
         0.1903, 0.0351]], grad_fn=<ReluBackward0>)
compare: 
 [[0.09951689 0.4849548  0.         0.         0.         0.
  0.12164748 0.02840686 0.         0.         0.41483328 0.
  0.         0.         0.         0.         0.         0.06903677
  0.0445093  0.33258596]
 [0.         0.29062638 0.         0.         0.         0.08020182
  0.3360821  0.10405582 0.         0.         0.11287315 0.
  0.         0.         0.16699418 0.         0.17711927 0

In [11]:
# Get cpu or gpu device for training.
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

# Define model
"""
To define a neural network in PyTorch, we create a class that inherits from nn.Module.
We define the layers of the network in the __init__ function and specify how data will pass through the network in the forward function. 
"""


class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28 * 28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits


model = NeuralNetwork().to(device)
print(model)

Using cpu device
NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


## Optimizing the Model Parameters


In [12]:
# define loss and optimizer
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)

In [13]:
def train(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    model.train()

    for batch, (X, y) in enumerate(dataloader):
        X, y = X.to(device), y.to(device)

        # Compute prediction error
        pred = model(X)
        loss = loss_fn(pred, y)

        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if batch % 100 == 0:
            loss, current = loss.item(), batch * len(X)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")

In [14]:
def test(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    model.eval()
    test_loss, correct = 0, 0

    with torch.no_grad():
        for X, y in dataloader:
            X, y = X.to(device), y.to(device)
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()

    test_loss /= num_batches
    correct /= size

    print(
        f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n"
    )

In [15]:
epochs = 5

for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train(train_dataloader, model, loss_fn, optimizer)
    test(test_dataloader, model, loss_fn)

print("Done!")

Epoch 1
-------------------------------
loss: 2.292758  [    0/60000]
loss: 2.279260  [ 6400/60000]
loss: 2.256767  [12800/60000]
loss: 2.253330  [19200/60000]
loss: 2.236565  [25600/60000]
loss: 2.202304  [32000/60000]
loss: 2.220580  [38400/60000]
loss: 2.181467  [44800/60000]
loss: 2.179981  [51200/60000]
loss: 2.142879  [57600/60000]
Test Error: 
 Accuracy: 44.3%, Avg loss: 2.137590 

Epoch 2
-------------------------------
loss: 2.151827  [    0/60000]
loss: 2.140122  [ 6400/60000]
loss: 2.077626  [12800/60000]
loss: 2.089816  [19200/60000]
loss: 2.036995  [25600/60000]
loss: 1.976463  [32000/60000]
loss: 2.004828  [38400/60000]
loss: 1.930176  [44800/60000]
loss: 1.938018  [51200/60000]
loss: 1.841922  [57600/60000]
Test Error: 
 Accuracy: 56.9%, Avg loss: 1.850392 

Epoch 3
-------------------------------
loss: 1.894083  [    0/60000]
loss: 1.859828  [ 6400/60000]
loss: 1.739984  [12800/60000]
loss: 1.767245  [19200/60000]
loss: 1.658980  [25600/60000]
loss: 1.619920  [32000/600

## Saving and Loding Models

In [16]:
# torch.save(model.state_dict(), "model.pth")
# print("Saved PyTorch Model State to model.pth")

# model = NeuralNetwork()
# model.load_state_dict(torch.load("model.pth"))

In [17]:
classes = [
    "T-shirt/top",
    "Trouser",
    "Pullover",
    "Dress",
    "Coat",
    "Sandal",
    "Shirt",
    "Sneaker",
    "Bag",
    "Ankle boot",
]

model.eval()
x, y = test_data[0][0], test_data[0][1]
with torch.no_grad():
    pred = model(x)
    predicted, actual = classes[pred[0].argmax(0)], classes[y]
    print(f'Predicted: "{predicted}", Actual: "{actual}"')

Predicted: "Ankle boot", Actual: "Ankle boot"
