In [1]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

In [22]:
import numpy as np

## Working with data


In [2]:
# Download training data from open datasets.
training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor(),
)

# Download test data from open datasets.
test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor(),
)

  0%|          | 0/26421880 [00:00<?, ?it/s]

Extracting data/FashionMNIST/raw/train-images-idx3-ubyte.gz to data/FashionMNIST/raw



  0%|          | 0/29515 [00:00<?, ?it/s]

Extracting data/FashionMNIST/raw/train-labels-idx1-ubyte.gz to data/FashionMNIST/raw



  0%|          | 0/4422102 [00:00<?, ?it/s]

Extracting data/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to data/FashionMNIST/raw



  0%|          | 0/5148 [00:00<?, ?it/s]

Extracting data/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to data/FashionMNIST/raw



In [3]:
batch_size = 64

# Create data loaders.
train_dataloader = DataLoader(training_data, batch_size=batch_size)
test_dataloader = DataLoader(test_data, batch_size=batch_size)

for X, y in test_dataloader:
  print(f"Shape of X [N, C, H, W]: {X.shape}")
  print(f"Shape of y: {y.shape} {y.dtype}")
  break

Shape of X [N, C, H, W]: torch.Size([64, 1, 28, 28])
Shape of y: torch.Size([64]) torch.int64


In [7]:
'''
N: number of instaces
C: channel?
H: height
W: width
'''

'\nN: number of instaces\nC: channel?\nH: height\nW: width\n'

## Creating Models


In [13]:
# simple situation
# Ref. https://pytorch.org/tutorials/beginner/basics/buildmodel_tutorial.html
input_image = torch.rand(3, 28, 28)
print(input_image.size())

torch.Size([3, 28, 28])


In [18]:
# flatten -> [3, 28*28]
flatten = nn.Flatten()
flat_image = flatten(input_image)
print(flat_image.size())
print(flat_image)

torch.Size([3, 784])
tensor([[0.5433, 0.3418, 0.3888,  ..., 0.7980, 0.4069, 0.6479],
        [0.8799, 0.4713, 0.9816,  ..., 0.7971, 0.1539, 0.3975],
        [0.6140, 0.8910, 0.6566,  ..., 0.3116, 0.2316, 0.9055]])


In [41]:
# value * weight
layer1 = nn.Linear(in_features=28 * 28, out_features=20)  # fully connected
hidden1 = layer1(flat_image)  # linear transformation (calc hiddlen unit value)
print(hidden1.size())
print(hidden1)

torch.Size([3, 20])
tensor([[ 0.1342,  0.2033,  0.5575,  0.4375,  0.2087,  0.9226, -0.2905, -0.3054,
          0.8958,  0.0459, -0.2880, -0.1285,  0.0481, -0.0102, -0.4472, -0.2859,
         -0.0291,  0.2186, -0.7362,  0.1767],
        [ 0.0621,  0.5183,  0.1368,  0.1004,  0.4541,  0.8500, -0.3177, -0.2868,
          0.5549,  0.2838,  0.1924, -0.1075, -0.1319,  0.2031, -0.5142, -0.2983,
         -0.3614,  0.0679, -0.2935,  0.3441],
        [-0.0605,  0.4426,  0.2652,  0.2357, -0.1846,  0.9035, -0.4481, -0.3386,
          0.4510,  0.2209, -0.4812, -0.1850,  0.1147,  0.4927, -0.3544,  0.1058,
         -0.2763,  0.0252,  0.0142,  0.1597]], grad_fn=<AddmmBackward0>)


In [46]:
# weight
print(layer1.weight.shape)
print(layer1.weight)

# bias
print(layer1.bias)

torch.Size([20, 784])
Parameter containing:
tensor([[ 0.0169,  0.0224, -0.0092,  ..., -0.0342, -0.0003, -0.0029],
        [ 0.0070,  0.0247,  0.0296,  ..., -0.0203, -0.0153,  0.0154],
        [ 0.0179, -0.0333,  0.0020,  ...,  0.0304, -0.0271, -0.0342],
        ...,
        [ 0.0260,  0.0102, -0.0124,  ..., -0.0323, -0.0275,  0.0302],
        [-0.0012,  0.0190,  0.0074,  ..., -0.0222, -0.0289,  0.0214],
        [ 0.0320, -0.0232,  0.0066,  ..., -0.0310, -0.0304,  0.0249]],
       requires_grad=True)
Parameter containing:
tensor([ 0.0356, -0.0334,  0.0222,  0.0215, -0.0271, -0.0328,  0.0328,  0.0145,
         0.0065,  0.0352,  0.0205, -0.0083, -0.0219,  0.0131,  0.0020,  0.0142,
        -0.0316, -0.0156,  0.0204, -0.0274], requires_grad=True)


In [30]:
# ReLU
hidden_activate = nn.ReLU()(hidden1)
print(hidden_activate)


# compare
def relu(x):
  return np.maximum(0, x)


print('compare: \n', relu(hidden1.detach().numpy()))

tensor([[0.0000, 0.2276, 0.0755, 0.0000, 0.0699, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.2862, 0.0113, 0.0000, 0.0000, 0.3345, 0.0000, 0.0000,
         0.4429, 0.0000],
        [0.0223, 0.3098, 0.3799, 0.0000, 0.0000, 0.1425, 0.0000, 0.2542, 0.0000,
         0.0000, 0.0000, 0.6239, 0.0000, 0.0000, 0.0000, 0.5216, 0.0316, 0.0000,
         0.2692, 0.0000],
        [0.0000, 0.1740, 0.1599, 0.0000, 0.0490, 0.0105, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.2655, 0.0000, 0.0000, 0.0000, 0.4099, 0.0000, 0.0000,
         0.0428, 0.0000]], grad_fn=<ReluBackward0>)
compare: 
 [[0.         0.22763467 0.07549297 0.         0.06993171 0.
  0.         0.         0.         0.         0.         0.2861728
  0.01131467 0.         0.         0.33452192 0.         0.
  0.44294244 0.        ]
 [0.02233453 0.30984586 0.3798543  0.         0.         0.14248651
  0.         0.25422323 0.         0.         0.         0.6239005
  0.         0.         0.         0.52158266 0.0315

In [31]:
# Get cpu or gpu device for training.
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

# Define model
'''
To define a neural network in PyTorch, we create a class that inherits from nn.Module.
We define the layers of the network in the __init__ function and specify how data will pass through the network in the forward function. 
'''


class NeuralNetwork(nn.Module):

  def __init__(self):
    super(NeuralNetwork, self).__init__()
    self.flatten = nn.Flatten()
    self.linear_relu_stack = nn.Sequential(nn.Linear(28 * 28, 512), nn.ReLU(),
                                           nn.Linear(512, 512), nn.ReLU(),
                                           nn.Linear(512, 10))

  def forward(self, x):
    x = self.flatten(x)
    logits = self.linear_relu_stack(x)
    return logits


model = NeuralNetwork().to(device)
print(model)

Using cpu device
NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


## Optimizing the Model Parameters


In [33]:
# define loss and optimizer
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)

In [34]:
def train(dataloader, model, loss_fn, optimizer):
  size = len(dataloader.dataset)
  model.train()

  for batch, (X, y) in enumerate(dataloader):
    X, y = X.to(device), y.to(device)

    # Compute prediction error
    pred = model(X)
    loss = loss_fn(pred, y)

    # Backpropagation
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if batch % 100 == 0:
      loss, current = loss.item(), batch * len(X)
      print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")

In [35]:
def test(dataloader, model, loss_fn):
  size = len(dataloader.dataset)
  num_batches = len(dataloader)
  model.eval()
  test_loss, correct = 0, 0

  with torch.no_grad():
    for X, y in dataloader:
      X, y = X.to(device), y.to(device)
      pred = model(X)
      test_loss += loss_fn(pred, y).item()
      correct += (pred.argmax(1) == y).type(torch.float).sum().item()

  test_loss /= num_batches
  correct /= size

  print(
      f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n"
  )

In [36]:
epochs = 5

for t in range(epochs):
  print(f"Epoch {t+1}\n-------------------------------")
  train(train_dataloader, model, loss_fn, optimizer)
  test(test_dataloader, model, loss_fn)

print("Done!")

Epoch 1
-------------------------------
loss: 2.309794  [    0/60000]
loss: 2.296753  [ 6400/60000]
loss: 2.275776  [12800/60000]
loss: 2.262720  [19200/60000]
loss: 2.258513  [25600/60000]
loss: 2.221460  [32000/60000]
loss: 2.226047  [38400/60000]
loss: 2.197746  [44800/60000]
loss: 2.191819  [51200/60000]
loss: 2.158185  [57600/60000]
Test Error: 
 Accuracy: 46.0%, Avg loss: 2.156168 

Epoch 2
-------------------------------
loss: 2.167736  [    0/60000]
loss: 2.167184  [ 6400/60000]
loss: 2.103154  [12800/60000]
loss: 2.116186  [19200/60000]
loss: 2.080446  [25600/60000]
loss: 2.006286  [32000/60000]
loss: 2.038419  [38400/60000]
loss: 1.960451  [44800/60000]
loss: 1.958233  [51200/60000]
loss: 1.896353  [57600/60000]
Test Error: 
 Accuracy: 59.2%, Avg loss: 1.892941 

Epoch 3
-------------------------------
loss: 1.922152  [    0/60000]
loss: 1.911476  [ 6400/60000]
loss: 1.779484  [12800/60000]
loss: 1.820993  [19200/60000]
loss: 1.723938  [25600/60000]
loss: 1.656347  [32000/600

## Saving and Loding Models

In [37]:
# torch.save(model.state_dict(), "model.pth")
# print("Saved PyTorch Model State to model.pth")

# model = NeuralNetwork()
# model.load_state_dict(torch.load("model.pth"))

In [38]:
classes = [
    "T-shirt/top",
    "Trouser",
    "Pullover",
    "Dress",
    "Coat",
    "Sandal",
    "Shirt",
    "Sneaker",
    "Bag",
    "Ankle boot",
]

model.eval()
x, y = test_data[0][0], test_data[0][1]
with torch.no_grad():
  pred = model(x)
  predicted, actual = classes[pred[0].argmax(0)], classes[y]
  print(f'Predicted: "{predicted}", Actual: "{actual}"')

Predicted: "Ankle boot", Actual: "Ankle boot"


In [ ]:
# wip
# https://free.kikagaku.ai/tutorial/basic_of_deep_learning/learn/pytorch_basic